document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\"UTF-8\">");
document.writeln("<meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\" name=\"viewport\" />");
document.writeln("<meta content=\"yes\" name=\"apple-mobile-web-app-capable\" />");
document.writeln("<meta content=\"black\" name=\"apple-mobile-web-app-status-bar-style\" />");
document.writeln("<meta content=\"telephone=no\" name=\"format-detection\" />");
document.writeln("<title>国家空间科学数据中心(National Space Science Data Center)</title>");
document.writeln("<meta name=\"description\" content=\"\">");
document.writeln("<link rel=\"stylesheet\" href=\"../css/reset.css\">");
document.writeln("<link rel=\"stylesheet\" href=\"../css/style.css\">");
document.writeln("<link rel=\"stylesheet\" href=\"../css/news.css\" />");
document.writeln("<link rel=\"stylesheet\" href=\"../css/aboutus.css\" />");
document.writeln("<script src=\"../js/jquery-3.4.1.min.js\"></script>");
document.writeln("<script src=\"../html/index.js\"></script>");
document.writeln("</head>");
document.writeln("<body class=\"nssdc_bg\">");
document.writeln("<div class=\"footer\">");
document.writeln("<div class=\"footer_main\">");
document.writeln("<div class=\"footer_logo\">");
document.writeln("<img src=\"../img/logo-2-big.png\" />");
document.writeln("</div>");
document.writeln("<div class=\"footer_company\">");
document.writeln("<p><span>国家空间科学数据中心</span><span>版权所有</span></p>");
document.writeln("<p><span>京ICP备05061203号-26</span><span>京公网安备110402500029号</span></p>");
document.writeln("<p>建议浏览器：Firefox,Google Chrome</p>");
document.writeln("<p>建议分辨率：1920x1080</p>");
document.writeln("<p>技术支持：长春巨诚科技有限公司</p>");
document.writeln("</div>");
document.writeln("<div class=\"footer_biao\">");
document.writeln("<img src=\"../img/erweima.png\" />");
document.writeln("</div>");
document.writeln("<div class=\"footer_chat\">");
document.writeln("<p>联系电话：010-52804246</p>");
document.writeln("<p>E-mail：nssdc_service@nssc.ac.cn</p>");
document.writeln("<p>地址：北京市海淀区中关村南二条一号 </p>");
document.writeln("<p>邮编：100190 </p>");
document.writeln("<p>");
document.writeln("<a onclick=\"yjjy()\" style=\"cursor:pointer;text-decoration:none;\">意见反馈</a>");
document.writeln("</p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");