document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\"UTF-8\">");
document.writeln("<meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\" name=\"viewport\" />");
document.writeln("<meta content=\"yes\" name=\"apple-mobile-web-app-capable\" />");
document.writeln("<meta content=\"black\" name=\"apple-mobile-web-app-status-bar-style\" />");
document.writeln("<meta content=\"telephone=no\" name=\"format-detection\" />");
document.writeln("<title>国家空间科学数据中心(National Space Science Data Center)</title>");
document.writeln("<meta name=\"description\" content=\"\">");
document.writeln("<link rel=\"stylesheet\" href=\"../css/reset.css\">");
document.writeln("<link rel=\"stylesheet\" href=\"../css/style.css\">");
document.writeln("<link rel=\"stylesheet\" href=\"../css/news.css\" />");
document.writeln("<link rel=\"stylesheet\" href=\"../css/aboutus.css\" />");
document.writeln("<script src=\"../js/jquery-3.4.1.min.js\"></script>");
document.writeln("<script src=\"../html/index.js\"></script>");
document.writeln("<script src=\"http://www.nssdc.ac.cn/resources/assets/spv.js\"></script>");
document.writeln("</head>");
document.writeln("<body class=\"nssdc_bg\">");
document.writeln("<div class=\"nssdc_top\">");
document.writeln("<div class=\"nssdc_top_main\">");
document.writeln("<div class=\"nssdc_top_left\">");
document.writeln("<a href=\"https://www.escience.org.cn/\" target=\"_blank\" id=\"logo_tit1\"><img src=\"../img/toplogo.png\" />国家科技资源共享服务平台</a>");
document.writeln("<a href=\"https://www.escience.org.cn/\" target=\"_blank\" id=\"logo_tit2\" style=\"display: none;\"><img src=\"../img/toplogo.png\" />国家科技资源共享服务平台</a>");
//document.writeln("<a href=\"../html/index.html\" id=\"logo_tit2\" style=\"display: none;\"><img src=\"../img/logo-2-big.png\" />国家空间科学数据中心</a>");
document.writeln("</div>");
document.writeln("<div class=\"menubtn\" id=\"menubtn\" onclick=\"menu()\">");
document.writeln("<img src=\"../img/menu.png\" />");
document.writeln("</div>");
document.writeln("<div class=\"menu subNavBox\">");
document.writeln("<div class=\"nologin_right\" id=\"wdl\"><a onclick=\"qdtz()\" style=\"cursor:pointer;text-decoration:none;\">登录/注册</a></div>");
document.writeln("<div class=\"login_div\" id=\"ydl\">");
document.writeln("<div class=\"login_state\">");
document.writeln("<img src=\"../img/photo_login.png\" />");
document.writeln("<span id=\"dlmc\"></span>");
document.writeln("</div>");
document.writeln("<ul class=\"login_ul\">");
document.writeln("<li>");
document.writeln("<a href=\"https://umt.nssdc.ac.cn/usermanager/manager/update?lang=zh\">");
document.writeln("<img src=\"../img/pinfo_icon.png\" />");
document.writeln("<span>修改个人信息</span>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\"https://umt.nssdc.ac.cn/usermanager/manager/updatePwd?lang=zh\">");
document.writeln("<img src=\"../img/pwd_icon.png\" />");
document.writeln("<span>修改密码</span>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li id=\"htgl\">");
document.writeln("<a onclick=\"glht()\">");
document.writeln("<img src=\"../img/manage.png\" />");
document.writeln("<span>管理后台</span>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a onclick=\"zx()\" id=\"zx\">");
document.writeln("<img src=\"../img/logout.png\" />");
document.writeln("<span>退出</span>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<div class=\"nssdc_top_right\">");
document.writeln("<a onclick=\"wdfw()\" style=\"cursor:pointer;\"><span>我的访问</span></a>");
document.writeln("<a onclick=\"sjzc()\" style=\"cursor:pointer;\"><span>数据政策</span></a>");
document.writeln("<a href=\"service.html\"><span>典型服务</span></a>");
document.writeln("<a href=\"help.html\"><span>帮助中心</span></a>");
document.writeln("<a onclick=\"yjjy()\" style=\"cursor:pointer;\"><span>意见建议</span></a>");
document.writeln("<a href=\"aboutus_center.html\"><span>关于我们</span></a>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");