/*
 * File: app/view/TaskInfoPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppPlat.view.TaskInfoPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.taskinfopanel',

    height: 50,
    maxHeight: 50,
    minHeight: 50,
    collapsible: true,
    animCollapse: true,
    padding:'0 0 0 0',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});