/**
 * 修改 by 杜鹏宇 on 2014/07/10
 */

/*
 * File: app/view/OuterCenterPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppPlat.view.StructDesign.StructDesignPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.structdesignpanel',

    requires: [
        'AppPlat.view.StructDesign.ModulePanel',
        'AppPlat.view.StructDesign.WorkTabPanel',
        'Ext.tab.Panel'
    ],

    width: 400,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [

                {
                    xtype: 'modulepanel',
                    region: 'east',

                    collapseMode: 'mini',
                    preventHeader: true
                },
//                {
//                    xtype: 'worktabpanel',
//                    region: 'center'
//
//
//                }
                {
                    xtype: 'structurescenepanelc',
                    region: 'center'
                }
            ]
        });

        me.callParent(arguments);
    }

});