/**
 * 修改 by 杜鹏宇 on 2014/8/24
 */

/*
 * File: app/view/StructureScenePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StructDesignApp.view.StructureScenePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.structurescenepanel',
    itemId: 'structureScenePanel',
    titleAlign:'center',
    html: '<div id="structDesign"></div>',
    dockedItems: [{
        dock: 'bottom',
        height:20,
        padding:'1 0 0 0',
        itemId:'structureSceneDockedItems',
        items: [
            {
                margin: '0 0 0 400',
                itemId: 'fileNameLbl',
                text: '新建卫星结构文件',
                disabled: true,
                xtype:'label'
            }
        ]
    }],
    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});